# Generated by Django 3.2.7 on 2021-10-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='login',
        ),
        migrations.AddField(
            model_name='tasks',
            name='executor',
            field=models.CharField(default=None, max_length=60, verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default='default', max_length=40, unique=True, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=30, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(default='Разработчик', max_length=40, verbose_name='Роль'),
        ),
    ]
