# Generated by Django 3.2.7 on 2021-10-12 17:18

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211012_0947'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='tasks',
            name='tittle',
            field=models.CharField(max_length=75, unique=True, verbose_name='Заголовок'),
        ),
    ]
